name: build

on: push

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - name: checkout emacs repo
        uses: actions/checkout@v2
        with:
          repository: emacs-mirror/emacs.git
          ref: emacs-27.1

      - name: compile emacs
        id: compile_emacs
        run: |
          ./configure \
             --with-ns \
             --without-dbus \
             --with-imagemagick \
             --disable-ns-self-contained

          make
