name: build

on: push

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - name: checkout build-emacs repo
        uses: actions/checkout@v2
        with:
          repository: caldwell/build-emacs

      - name: compile emacs
        id: compile_emacs
        run: |
          ./fetch-emacs-from-ftp -v ftp://ftp.gnu.org/pub/gnu/emacs
          ls *.bz2
          ./build-emacs-from-tar -v -j 8 emacs-27.1.tar.bz2 release
          ./combine-and-package -v Emacs-27.1-10.12-x86_64.tar.bz2
